matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - valgrind
      env:
        - MATRIX_EVAL="CC=gcc-6"

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - valgrind
      env:
        - MATRIX_EVAL="CC=gcc-7"

language: c
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test
